// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaGHwl2IgWa46J8OMZXDZn59RnF_IGsyA',
    appId: '1:414166164696:web:c4885a33c62c732b6e23ad',
    messagingSenderId: '414166164696',
    projectId: 'flutter-iii-8a868',
    authDomain: 'flutter-iii-8a868.firebaseapp.com',
    storageBucket: 'flutter-iii-8a868.appspot.com',
    measurementId: 'G-5FYW23R0KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp1OVwmlHFMJ_IM_j9rYsK75DcvUxzXBU',
    appId: '1:414166164696:android:812dd951ef1bf34e6e23ad',
    messagingSenderId: '414166164696',
    projectId: 'flutter-iii-8a868',
    storageBucket: 'flutter-iii-8a868.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqRXDO_MCV4QX6zhh-WlC4_DbosBqxY_M',
    appId: '1:414166164696:ios:8d36f57c673a6de36e23ad',
    messagingSenderId: '414166164696',
    projectId: 'flutter-iii-8a868',
    storageBucket: 'flutter-iii-8a868.appspot.com',
    iosClientId: '414166164696-1o44u44h9hv82e14slumteo4fus57t1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.com',
  );
}
